services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - microservices
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80" # HTTP entrypoint
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - microservices
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hubdb
    ports:
      - "5433:5432" # Host:Container
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
      target: dev
    container_name: notification-service
    command: ["air", "-c", ".air.toml"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    working_dir: /app/services/notification-service
    env_file:
      - ./services/notification-service/.env
    ports:
      - "5200:5200"
    volumes:
      - ./services/notification-service:/app/services/notification-service
      - ./:/app/
      - /app/services/notification-service/tmp
    networks:
      - microservices
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: ./services/users-service/Dockerfile
      target: dev
    container_name: user-service
    command: ["air", "-c", ".air.toml"]
    working_dir: /app/services/users-service
    ports:
      - "5000:5000" # HTTP port
      - "50051:50051" # gRPC port
    volumes:
      - ./services/users-service:/app/services/users-service
      - ./:/app/
      - /app/services/users-service/tmp # Exclude tmp folder from sync
    env_file:
      - ./services/users-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - microservices
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/api/users`) || PathPrefix(`/api/auth`)"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.routers.users.middlewares=users-ratelimit"
      - "traefik.http.services.users.loadbalancer.server.port=5000"
      # Rate Limiting
      - "traefik.http.middlewares.users-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.users-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.users-ratelimit.ratelimit.period=1s"

  projects-service:
    build:
      context: .
      dockerfile: ./services/projects-service/Dockerfile
      target: dev
    container_name: projects-service
    command: ["air", "-c", ".air.toml"]
    working_dir: /app/services/projects-service
    ports:
      - "5100:5100" # HTTP port
    volumes:
      - ./services/projects-service:/app/services/projects-service
      - ./:/app/
      - /app/services/projects-service/tmp # Exclude tmp folder from sync
    env_file:
      - ./services/projects-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - microservices
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.projects.rule=PathPrefix(`/api/projects`)"
      - "traefik.http.routers.projects.entrypoints=web"
      - "traefik.http.routers.projects.middlewares=projects-ratelimit"
      - "traefik.http.services.projects.loadbalancer.server.port=5100"
      # Rate Limiting
      - "traefik.http.middlewares.projects-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.projects-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.projects-ratelimit.ratelimit.period=1s"

volumes:
  postgres-data:
    driver: local

networks:
  microservices:
    driver: bridge
